### ISSUE TITLE
Fix links in README.md

### ISSUE THREAD

**Issue by hammadmajid** [hammadmajid/algorithms#33]
**Describe the bug**
Invalid links in README.md. These links don't work on [GitHub Pages](https://hammadmajid.github.io/algorithms).

```markdown
[code_of_conduct_link]: ./CODE_OF_CONDUCT.md
[license_link]: ./LICENSE
[contributing_link]: ./CONTRIBUTIING.md
```
**To Reproduce**
1. Go to [GitHub Pages](https://hammadmajid.github.io/algorithms).
2. Scroll down to [meta] section.
3. Click on any of the first three.

**Expected behavior**
GitHub blob of each file

**Comment by MaximSmolskiy** [comment]
@hammadmajid Are you sure the links don't work? For me they work
![Снимок экрана от 2022-12-04 00-05-33](https://user-images.githubusercontent.com/25690822/205462110-84aff2eb-4522-4d14-90b9-06310a846b5a.png)
![Снимок экрана от 2022-12-04 00-05-40](https://user-images.githubusercontent.com/25690822/205462111-07073dd3-8428-48a3-a841-19b5f931c51c.png)

There is only one problem with
```
[contributing_link]: ./CONTRIBUTIING.md
```
because there is a typo in `CONTRIBUTIING` - double `II` instead of one. I'll make a pr with this fix.
